[package]
build = "build.rs"
description = "Zero setup cross compilation and cross testing"
documentation = "https://github.com/cross-rs/cross"
keywords = ["cross", "compilation", "testing", "tool"]
license = "MIT OR Apache-2.0"
name = "cross"
repository = "https://github.com/cross-rs/cross"
version = "0.2.1"
edition = "2021"

[features]
default = []
dev = []

[workspace]
members = ["xtask"]

[dependencies]
atty = "0.2"
clap = { version = "3.2.2", features = ["derive", "unstable-v4"] }
color-eyre = "0.6"
eyre = "0.6"
thiserror = "1"
home = "0.5"
rustc_version = "0.4"
toml = "0.5"
which = { version = "4", default_features = false }
shell-escape = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_ignored = "0.1.2"
shell-words = "1.1.0"
ctrlc = { version = "3.2.2", features = ["termination"] }
directories = "4.0.1"
tempfile = "3.3.0"

[target.'cfg(not(windows))'.dependencies]
nix = { version = "0.24", default-features = false, features = ["user"] }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }
dunce = "1"

[profile.release]
lto = true

[dev-dependencies]
regex = "1"
once_cell = "1"
walkdir = "2"
