[alias]
xtask = ["run", "-p", "xtask", "--"]
build-docker-image = ["xtask", "build-docker-image"]
changeset = ["run", "-p", "changeset", "--"]
build-changeset = ["changeset", "build"]
validate-changeset = ["changeset", "validate"]
